name: ci
on:
  push:
    branches:
      - wiki
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
          enable-cache: true
      - name: Generate Cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Setup Actions Cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - name: Install Dependencies
        run: uv sync
      - name: Deploy to Github Pages
        run: uv run mkdocs gh-deploy --force
      - name: Prune uv Cache
        run: uv cache prune --ci
